sed -i 's/colorscheme\.c/tui\/colorscheme.c/' Makefile
sed -i 's/colorscheme\.o/tui\/colorscheme.o/' Makefile
sed -i 's/display\.c/tui\/display.c/' Makefile
sed -i 's/display\.o/tui\/display.o/' Makefile
sed -i 's/tcap\.c/tui\/tcap.c/' Makefile
sed -i 's/tcap\.o/tui\/tcap.o/' Makefile
sed -i 's/ncurses\.c/tui\/ncurses.c/' Makefile
sed -i 's/ncurses\.o/tui\/ncurses.o/' Makefile
sed -i 's/term_wrapper\.c/tui\/term_wrapper.c/' Makefile
sed -i 's/term_wrapper\.o/tui\/term_wrapper.o/' Makefile
sed -i 's/colors_engine\.c/tui\/colors_engine.c/' Makefile
sed -i 's/colors_engine\.o/tui\/colors_engine.o/' Makefile
sed -i 's/render_plugin\.c/tui\/render_plugin.c/' Makefile
sed -i 's/render_plugin\.o/tui\/render_plugin.o/' Makefile
